openapi: 3.0.3
info:
  title: Hotel
  description: ZZPJ 2023
  version: 1.0.0
paths:
  /hotels:
    get:
      tags:
        - hotelsCollector/hotel
      description: Returns all hotels
      operationId: getHotels
      responses:
        '200':
          description: List of hotels
          content:
            application/json:
              schema:
                $ref: ../defs/HotelListResponse.yaml
        '404':
          description: Not found any hotel


  /hotels/hotel:
    post:
      tags:
        - hotelsCollector/hotel
      description: Add hotel
      operationId: addHotel
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../defs/HotelRequest.yaml
      responses:
        '201':
          description: Hotel created
          content:
            application/json:
              schema:
                $ref: ../defs/HotelResponse.yaml

  /hotels/hotel/{id}:
    get:
      tags:
        - hotelsCollector/hotel
      description: Get hotel with given id
      operationId: getHotel
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Hotel with given id
          content:
            application/json:
              schema:
                $ref: ../defs/HotelResponse.yaml
        '404':
          description: Not found hotel
    delete:
      tags:
        - hotelsCollector/hotel
      description: Delete hotel with given id
      operationId: deleteHotel
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Hotel with given id deleted
        '404':
          description: Not found hotel

  /hotels/hotel/{id}/room:
    post:
      tags:
        - hotelsCollector/hotel/room
      description: Add room to hotel with given id
      operationId: addRoom
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../defs/RoomRequest.yaml
      responses:
        '200':
          description: Room added to hotel with given id
        '404':
          description: Room not found

  /hotels/hotel/{id}/room/{idRoom}:
    get:
      tags:
        - hotelsCollector/hotel/room
      description: Get room with given id in hotel with given id
      operationId: getRoomInHotel
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: idRoom
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Room with given id in hotel with given id
          content:
            application/json:
              schema:
                $ref: ../defs/RoomResponse.yaml
        '404':
          description: Not found hotel
    delete:
      tags:
        - hotelsCollector/hotel/room
      description: Delete room with given id in hotel with given id
      operationId: deleteRoomInHotel
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: idRoom
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Room removed from hotel with given id
        '404':
          description: Room not found

  /hotels/hotel/{id}/rooms:
    get:
      tags:
        - hotelsCollector/hotel/room
      description: Returns all rooms in hotel with given id
      operationId: getRoomsInHotel
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of rooms in hotel with given id
          content:
            application/json:
              schema:
                $ref: ../defs/RoomListResponse.yaml
        '404':
          description: Not found any room