stages:
  - build
  - build_on_branch
  - test

build:
  image: maven:3.8.4-openjdk-17
  stage: build
  script:
    - mvn install -DskipTests=true

build_on_branch:
  image: maven:3.8.4-openjdk-17
  stage: build_on_branch
  only:
    - gitlab-ci-cd
  script:
    - mvn install -DskipTests=true

test:
  image: maven:3.8.4-openjdk-17
  stage: test
  script:
    - mvn test